### ISSUE TITLE
PDF attachment not working

### ISSUE THREAD

**Issue by Joesmi** [gryphonshafer/Email-Mailer#3]
Email::Mailer::send() uses quoted-printable encoding for attachments. This doesn't work for a PDF as per my tests, it becomes corrupted/unreadable.
With base64 encoding the PDF gets delivered intact. Also base64 it seems to be the recommended encoding for binary files.
Please would you mind changing quoted-printable to base64 or add encoding as a parameter in the attachment hash - besides ctype, content, name.
Thanks!

**Comment by gryphonshafer** [comment]
This is fixed in 5a26484, which is released as v1.08 to CPAN. (It'll take a couple hours or so for CPAN to process it and make it available to the universe.)
