### ISSUE TITLE
Missing Samples

### ISSUE THREAD

**Issue by dominic01** [gryphonshafer/Email-Mailer#4]
Do you have full sample scripts? It is not available in the documentation.

**Comment by gryphonshafer** [comment]
I don't understand what you mean by "full sample scripts". The documentation contains 8 examples. The first lines of the synopsis is:

```
use Email::Mailer;
my ( $to, $from, $subject, $text, $html );

# send a simple text email
Email::Mailer->send(
    to      => $to,
    from    => $from,
    subject => $subject,
    text    => $text,
);
```

If you define `$to, $from, $subject, $text, $html`, then it works as a stand-alone program.
